# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


repos:
    # General hooks.
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: detect-aws-credentials
        -   id: detect-private-key
    -   repo: https://github.com/Yelp/detect-secrets
        rev: v1.5.0
        hooks:
        -   id: detect-secrets

    # Language specific hooks.
    - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
        rev: v0.8.4
        hooks:
            # Run the linter.
            - id: ruff
            args: [ --fix ]
            # Run the formatter.
            - id: ruff-format
